name: 'Lint schema'
on:
  pull_request:
    branches:
      - main
    paths:
      - '**.json'

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changed files
        id: changes
        run: |
          echo "ALL=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
          echo "JSON=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .json$ | xargs)" >> $GITHUB_OUTPUT

  lint:
    runs-on: ubuntu-latest
    needs: changedfiles
    if: ${{needs.changedfiles.outputs.json}}
    steps:
      - name: Install schemalint
        run: |
          export SCHEMALINT_VERSION=v0.0.1
          wget -q -O ${HOME}/schemalint.tar.gz https://github.com/giantswarm/schemalint/releases/download/${SCHEMALINT_VERSION}/schemalint-${SCHEMALINT_VERSION}-linux-amd64.tar.gz
          cd ${HOME} && tar xvzf schemalint.tar.gz
          cp ${HOME}/schemalint-${SCHEMALINT_VERSION}-linux-amd64/schemalint ${HOME}/schemalint
          test -x ${HOME}/schemalint
      
      - name: Echo changed files
        run: |
          echo ${{needs.changedfiles.outputs.JSON}}

      - name: Lint all changed schema files
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          for file in ${{needs.changedfiles.outputs.JSON}}; do
            echo "$file was changed"
            ${HOME}/schemalint $file
          done
